import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Head from 'next/head'

import Navbar from '../../components/navbar'
import Footer from '../../components/footer'

export default function DrinkDetail() {
    const router = useRouter()
    const { did } = router.query

    const [state, setState] = useState({
        posts: []
    });

    useEffect(() => {
        if(did) {
            fetch(`https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=${did}`)
                .then(response => response.json())
                .then(result => {
                    console.log(result.drinks[0])
                    setState({ posts: result.drinks[0] })
            })
        }
    }, [did])

    if(!state.posts) {
        return (
            <div className='pt-100 text-center'>
                <h2>No Data Found</h2>
                <a href='/'><strong>Go Back To Home</strong></a>
            </div>
        )
    }

    const item = state.posts;

    let ingredients = [];
    if (item.strIngredient1) { ingredients.push(<li>{item.strIngredient1}</li>) }
    if (item.strIngredient2) { ingredients.push(<li>{item.strIngredient2}</li>) }
    if (item.strIngredient3) { ingredients.push(<li>{item.strIngredient3}</li>) }
    if (item.strIngredient4) { ingredients.push(<li>{item.strIngredient4}</li>) }
    if (item.strIngredient5) { ingredients.push(<li>{item.strIngredient5}</li>) }
    if (item.strIngredient6) { ingredients.push(<li>{item.strIngredient6}</li>) }
    if (item.strIngredient7) { ingredients.push(<li>{item.strIngredient7}</li>) }
    if (item.strIngredient8) { ingredients.push(<li>{item.strIngredient8}</li>) }
    if (item.strIngredient9) { ingredients.push(<li>{item.strIngredient9}</li>) }
    if (item.strIngredient10) { ingredients.push(<li>{item.strIngredient10}</li>) }
    if (item.strIngredient11) { ingredients.push(<li>{item.strIngredient11}</li>) }
    if (item.strIngredient12) { ingredients.push(<li>{item.strIngredient12}</li>) }
    if (item.strIngredient13) { ingredients.push(<li>{item.strIngredient13}</li>) }
    if (item.strIngredient14) { ingredients.push(<li>{item.strIngredient14}</li>) }
    if (item.strIngredient15) { ingredients.push(<li>{item.strIngredient15}</li>) }

    return (
        <div className='w-full'>
            <Head>
                <title>Next Mini Cocktailspedia</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar/>
            <div className='px-24 py-16'>
                { item &&
                    <div className='flex flex-row justify-center items-center gap-16'>
                        <div className='w-1/3'>
                            <img src={item.strDrinkThumb} alt='Img Cocktail' className='w-100'/>
                        </div>
                        <div className='w-2/3 flex flex-col justify-center items-start gap-5'>
                            <h2 className='font-bold text-3xl'>{item.strDrink}</h2>
                            <span><strong>Ingredients : </strong><br/><ul>{ingredients}</ul></span>
                            <p><strong>Glass : </strong><br/>{item.strGlass}</p>
                            <p><strong>Instructions : </strong><br/>{item.strInstructions}</p>
                        </div>
                    </div>
                }
            </div>
            <Footer/>
        </div>
    )
}