import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

function DrinkPosts(props) {
    const item = props.drink
    return (
        <Link className={styles.card} href={`/drinkdetail/${item.idDrink}`}>
            <div className='cursor-pointer'>
                <Image src={`${item.strDrinkThumb}`} loader={() => item.strDrinkThumb} unoptimized alt='Cocktails Image' width={250} height={250}/>
                <p className='py-4 text-center font-medium text-base'>{item.strDrink}</p>
            </div>
        </Link>
    )
}

export default function DrinkList({ list }) {
    const [items, setItems] = useState(list)
    const [searchDrink, setSearchDrink] = useState('')

    useEffect(() => {
        if (!searchDrink) {
            setItems(list)
        } else {
            fetch(`https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${searchDrink}`)
                .then(response => response.json())
                .then(result => {
                    setItems(result.drinks)
            })
        }
    }, [list, searchDrink])

    return(
        <>
        <Head>
            <title>Next Mini Cocktailspedia</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <div className='px-24 py-16'>
                <h1 className='text-center mt-2 mb-4 font-bold text-3xl'>Welcome to Cocktailspedia !</h1>
                <form className='mt-6 mb-12 flex flex-row justify-center items-center'>
                    <input 
                        type="text" name="drinkSearchBar" id="drinkSearchBar"
                        className={styles.inputsearch} 
                        placeholder="Search here ..."
                        value={searchDrink}
                        onChange={(e) => setSearchDrink(e.target.value)}
                    />
                </form>
                { items 
                ?
                <div className='grid grid-cols-4 gap-8'>
                    { items.length > 0 && items.map(i => <DrinkPosts key={i.idDrink} drink={i} />)}
                </div>
                : 
                <div className='py-10 text-center'>
                    <h2 className='font-bold'>--- No Data Found ---</h2>
                </div>
                }
            </div>
        </Layout>
        </>
    )
}