import Head from 'next/head'

import DrinkList from './drinklist'
import Navbar from '../components/navbar'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title>Next Mini Cocktailspedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <DrinkList/>
      <Footer/>
    </div>
  )
}
